<?php

/**
 * 
 * Locale genérico para el catalán
 * @var array
 */

$default_locale = array(
	
	'aceptar' 	=> 'acceptar',
	'de'		=> 'de',
	'en'		=> 'en',
	'pagina'	=> 'pàgina',
	'paginas'	=> 'pàgines',

	'lista_dias' => array(
		'0'	=> 'dilluns',
		'1'	=> 'dimarts',
		'2'	=> 'dimecres',
		'3'	=> 'dijous',
		'4'	=> 'divendres',
		'5'	=> 'dissabte',
		'6'	=> 'diumenge'
	),

	'lista_meses' => array(
		'0'		=> 'gener',
		'1'		=> 'febrer',
		'2'		=> 'març',
		'3'		=> 'abril',
		'4'		=> 'maig',
		'5'		=> 'juny',
		'6'		=> 'juliol',
		'7'		=> 'agost',
		'8'		=> 'setembre',
		'9'		=> 'octubre',
		'10'	=> 'novembre',
		'11'	=> 'decembre'
	)
	
);

?>