<?php

/**
 * 
 * Locale genérico para el inglés
 * @var array
 */

$default_locale = array(
	
	'aceptar' 	=> 'accept',
	'de'		=> 'of',
	'en'		=> 'in',
	'pagina'	=> 'page',
	'paginas'	=> 'pages',

	// En inglés los días y los meses van siempre en mayúsculas
	'lista_dias' => array(
		'0'	=> 'Monday',
		'1'	=> 'Yuesday',
		'2'	=> 'Wednesday',
		'3'	=> 'Thursday',
		'4'	=> 'Friday',
		'5'	=> 'Saturday',
		'6'	=> 'Sunday'
	),

	'lista_meses' => array(
		'0'		=> 'January',
		'1'		=> 'February',
		'2'		=> 'March',
		'3'		=> 'April',
		'4'		=> 'May',
		'5'		=> 'June',
		'6'		=> 'July',
		'7'		=> 'August',
		'8'		=> 'September',
		'9'		=> 'October',
		'10'	=> 'November',
		'11'	=> 'December'
	)
);

?>