<?php

/**
 * 
 * Locale genérico para el castellano
 * @var array
 */

$default_locale = array(
	
	'aceptar' 	=> 'aceptar',
	'de'		=> 'de',
	'en'		=> 'en',
	'pagina'	=> 'página',
	'paginas'	=> 'páginas',
	
	'lista_dias' => array(
		'1'	=> 'lunes',
		'2'	=> 'martes',
		'3'	=> 'miércoles',
		'4'	=> 'jueves',
		'5'	=> 'viernes',
		'6'	=> 'sábado',
		'7'	=> 'domingo'
	),

	'lista_meses' => array(
		'1'		=> 'enero',
		'2'		=> 'febrero',
		'3'		=> 'marzo',
		'4'		=> 'abril',
		'5'		=> 'mayo',
		'6'		=> 'junio',
		'7'		=> 'julio',
		'8'		=> 'agosto',
		'9'		=> 'septiembre',
		'10'	=> 'octubre',
		'11'	=> 'noviembre',
		'12'	=> 'diciembre'
	)
);

?>